GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/1/

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "111"
}